// Extracts the Material "Filled" icons the app uses (Icons.Filled.* in the
// Compose sources) into one module, so no icon font or CDN is needed.
import { readFileSync, writeFileSync } from 'node:fs'
const names = `shopping_cart dns notifications account_balance_wallet support_agent swap_horiz refresh info
chevron_left chevron_right link link_off verified card_giftcard content_copy credit_card receipt_long autorenew
open_in_new security shield add_circle shopping_bag keyboard_arrow_left keyboard_arrow_right arrow_back arrow_forward
light_mode dark_mode bolt power_settings_new close data_usage palette download logout qr_code_2 share apps
check_circle error warning star star_half star_border storefront local_offer report send phone_iphone android
laptop smartphone desktop_windows add remove expand_more expand_less help schedule history person tune check sell
campaign reviews chat attach_file upload image ios_share add_to_home_screen install_mobile install_desktop
file_download vpn_key public language lock lock_open cloud_download visibility filter_list sort search
inventory_2 emoji_events speed timer edit delete more_vert notifications_active notifications_off
mark_email_read done_all qr_code layers category workspace_premium menu_book grid_view view_list
play_arrow stop arrow_upward swap_vert delete_sweep content_paste upload_file hub timer_off network_check delete_forever edit_off`.split(/\s+/).filter(Boolean)
const out = {}
for (const n of names) {
  const svg = readFileSync(`node_modules/@material-design-icons/svg/filled/${n}.svg`, 'utf8')
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map(m => m[1])
  const circles = [...svg.matchAll(/<circle[^>]*cx="([^"]+)"[^>]*cy="([^"]+)"[^>]*r="([^"]+)"/g)]
    .map(([, cx, cy, r]) => `M${+cx - +r},${cy}a${r},${r} 0 1,0 ${2 * r},0a${r},${r} 0 1,0 ${-2 * r},0`)
  out[n] = [...paths, ...circles].join(' ')
}
writeFileSync('src/components/icons.generated.ts',
  '// Generated by scripts/gen-icons.mjs from @material-design-icons/svg (Apache-2.0).\n' +
  'export const MaterialIcons: Record<string, string> = ' + JSON.stringify(out, null, 1) + '\n')
console.log(Object.keys(out).length, 'icons')
