package net.gozar.app

enum class Lang { EN, FA }

private val faDigits = charArrayOf('۰','۱','۲','۳','۴','۵','۶','۷','۸','۹')

fun localizeDigits(text: String, lang: Lang): String {
    if (lang != Lang.FA) return text
    val sb = StringBuilder(text.length)
    for (c in text) sb.append(if (c in '0'..'9') faDigits[c - '0'] else c)
    return sb.toString()
}
object Strings {

    private val en = mapOf(
        "connection" to "Connection",
        "shop" to "Shop",
        "ssh" to "SSH",
        "srv_checks" to "Server side",
        "pnl_checks" to "Panel side",
        "pnl_kind" to "Panel type",
        "pnl_url" to "Panel address",
        "pnl_user" to "Panel username",
        "pnl_pass" to "Panel password",
        "pnl_run" to "Run panel check",
        "pnl_running" to "Checking…",
        "pnl_part_reach" to "Panel address",
        "pnl_part_node" to "Entry node",
        "pnl_part_exit" to "Exit node",
        "pnl_part_host" to "Host settings",
        "pnl_part_inbound" to "Inbound",
        "pnl_part_route" to "Routing rule",
        "pnl_part_outbound" to "Outbound",
        "pnl_node_missing" to "No node in this panel serves this address",
        "pnl_node_down" to "The panel reports this node as unhealthy",
        "pnl_host_missing" to "No host entry matches this address",
        "pnl_host_disabled" to "This host is disabled in the panel",
        "pnl_host_mismatch" to "The config does not match the host settings",
        "pnl_inbound_unknown" to "No inbound tag on the matching host",
        "pnl_inbound_missing" to "The host points at an inbound that does not exist",
        "pnl_inbound_mismatch" to "The config does not match the inbound",
        "pnl_core_missing" to "No core contains this inbound",
        "pnl_outbound_missing" to "The routing rule points at an outbound that does not exist",
        "pnl_outbound_unknown" to "Could not read the outbound destination",
        "pnl_exit_missing" to "The exit server is not a node in this panel",
        "pnl_part_login" to "Admin login",
        "pnl_part_core" to "Core reported by panel",
        "pnl_part_uptime" to "Panel uptime",
        "pnl_no_url" to "Enter the panel address first",
        "pnl_unreachable" to "The panel did not answer at this address",
        "pnl_timeout" to "Timed out, check the port. Panels rarely run on 443",
        "pnl_tls" to "TLS failed, the panel certificate is not trusted. Only use an http:// address on a network you trust, it sends your password in the clear.",
        "pnl_dns" to "That address does not resolve",
        "pnl_refused" to "Connection refused, nothing is listening on that port",
        "pnl_bad_login" to "Panel rejected these credentials",
        "pnl_csrf" to "Panel refused the login as untrusted, check the address and TLS",
        "pnl_core_down" to "The panel reports the core is not running",
        "pnl_core_error" to "The panel reports a core error",
        "pnl_unknown" to "Could not be determined",
        "srv_via" to "Checked over SSH on %s",
        "srv_host" to "Run checks on",
        "srv_run" to "Run server checks",
        "srv_running" to "Checking…",
        "srv_part_listen" to "Port listening",
        "srv_part_core" to "Core process",
        "srv_part_firewall" to "Firewall",
        "srv_part_cert" to "Certificate expires",
        "srv_part_log" to "Recent core errors",
        "srv_part_load" to "Load average",
        "srv_no_listen" to "Nothing is bound to this port on the server",
        "srv_no_core" to "No proxy core process is running",
        "srv_fw_no_rule" to "No firewall rule found for this port",
        "srv_no_cert" to "No certificate served for this SNI on the local port",
        "srv_load_high" to "Load is above one core, the server is saturated",
        "srv_load_critical" to "Load is far above core count, the server is overloaded",
        "srv_unknown" to "Could not be determined",
        "ssh_add" to "Add host",
        "ssh_add_sub" to "Save a server to connect over SSH",
        "term_local" to "Local terminal",
        "term_local_sub" to "A shell on this device, inside the app sandbox",
        "term_running" to "Shell running",
        "term_stopped" to "Shell stopped",
        "ssh_state_off" to "Disconnected",
        "ssh_host_details" to "Server",
        "ssh_credentials" to "Credentials",
        "ssh_edit" to "Edit host",
        "ssh_empty" to "No SSH hosts yet",
        "ssh_empty_sub" to "Add a server to connect to it over SSH",
        "ssh_label" to "Label (optional)",
        "ssh_address" to "Host or IP",
        "ssh_port" to "Port",
        "ssh_username" to "Username",
        "ssh_password" to "Password",
        "ssh_direct" to "Connect directly",
        "ssh_direct_sub" to "Bypass the tunnel for this host.",
        "ssh_connect" to "Connect",
        "ssh_disconnect" to "Disconnect",
        "ssh_open_shell" to "Shell",
        "sftp" to "Files",
        "sftp_empty" to "This folder is empty",
        "sftp_failed" to "The server refused that operation",
        "sftp_upload" to "Upload",
        "sftp_new_folder" to "New folder",
        "sftp_folder_name" to "Folder name",
        "sftp_downloading" to "Downloading\u2026",
        "sftp_uploading" to "Uploading\u2026",
        "sftp_delete_title" to "Delete",
        "sftp_delete_q" to "Delete %s from the server? This cannot be undone.",
        "ssh_connecting" to "Connecting…",
        "ssh_connected" to "Connected",
        "ssh_via_tunnel" to "Through the tunnel",
        "ssh_via_direct" to "Direct connection",
        "ssh_delete_title" to "Delete host",
        "ssh_delete_q" to "Delete %s? This cannot be undone.",
        "ssh_err_auth" to "Authentication failed, check username and password",
        "ssh_err_host" to "Host could not be resolved",
        "ssh_err_timeout" to "Connection timed out",
        "ssh_err_refused" to "Connection refused, check the port",
        "ssh_err_proxy" to "Could not reach the tunnel, connect the VPN or use direct",
        "ssh_err_no_user" to "Username is required",
        "ssh_err_generic" to "Connection failed",
        "chain_through" to "Connect through",
        "chain_hint" to "Dial this config through another one, tunnel inside tunnel",
        "chain_none" to "Direct, no carrier",
        "chain_carrier" to "Carrier config",
        "home" to "Home",
        "debugger" to "Debugger",
        "debugger_title" to "Config Debugger",
        "dbg_offline" to "Offline",
        "dbg_undetermined" to "Could not be determined",
        "dbg_part_remote" to "Remote reachability",
        "dbg_part_core" to "Protocol handshake",
        "dbg_local_udp" to "UDP cannot be probed from this device",
        "dbg_handshake_failed" to "Handshake refused, check credentials and transport settings",
        "dbg_reality_refused" to "Server refused the handshake",
        "dbg_no_traffic" to "Tunnel is up but no traffic passes through it",
        "dbg_part_quota" to "Subscription",
        "dbg_sub_expired" to "Subscription has expired",
        "dbg_sub_exhausted" to "Subscription data is used up",
        "dbg_sub_low" to "Less than 10% of data left",
        "dbg_sub_ending" to "Subscription expires in under 3 days",
        "dbg_blocked" to "Blocked",
        "dbg_part_dns" to "DNS",
        "dbg_part_domain" to "Domain",
        "dbg_part_exposure" to "VPN exposure",
        "dbg_vpn_exposed" to "IP is exposed as VPN to strict services",
        "dbg_exit_blocked" to "Exit IP is blocked from your network",
        "dbg_part_tcp" to "TCP handshake",
        "dbg_part_tls" to "TLS handshake",
        "dbg_dns_fail" to "Address does not resolve",
        "dbg_domain_filtered" to "Domain is filtered from your network",
        "dbg_no_internet" to "No internet on this network",
        "dbg_addr_mismatch" to "Address is online but nothing is listening on this port",
        "dbg_addr_offline" to "Address is offline",
        "dbg_port_blocked" to "Port blocked by your network",
        "dbg_ip_blocked" to "IP is blocked from your network",
        "dbg_tls_cert" to "Certificate does not match the SNI, try allow insecure",
        "dbg_tls_cert_insecure" to "Certificate rejected even with allow insecure",
        "dbg_sni_blocked" to "SNI blocked, handshake reset",
        "dbg_sni_mismatch" to "Certificate rejected, the SNI may be broken",
        "dbg_sni_no_resolve" to "SNI domain does not exist",
        "dbg_sni_filtered" to "SNI domain is filtered on your network",
        "dbg_sni_no_tls13" to "SNI domain does not support TLS 1.3",
        "dbg_sni_unreachable" to "SNI domain is not reachable",
        "dbg_sni_timeout" to "SNI not reachable, handshake stalled",
        "dbg_host_blocked" to "Host header domain not reachable",
        "dbg_info" to "Connection details",
        "dbg_part_transport" to "Method",
        "dbg_part_entry" to "Entry",
        "dbg_part_ip" to "Exit",
        "dbg_connecting" to "Connecting to this config",
        "dbg_part_iptype" to "IP type",
        "dbg_part_risk" to "Reputation",
        "dbg_exit_offline" to "Connect to read the exit IP",
        "dbg_part_flags" to "Detected as",
        "dbg_rep_flagged" to "Known VPN, proxy, Tor or abuse range",
        "dbg_rep_unavailable" to "Unavailable",
        "dbg_state" to "Connection state",
        "dbg_healthy" to "Healthy",
        "dbg_timeout" to "Timeout",
        "dbg_broken" to "Broken",
        "dbg_testing" to "Testing",
        "dbg_ping" to "Ping",
        "dbg_recheck" to "Re-check",
        "dbg_no_config" to "No config selected. Pick a server first.",
        "dbg_client_checks" to "Client side",
        "dbg_all_ok" to "All parts valid",
        "dbg_issues" to "%s broken, %s warnings",
        "dbg_part_protocol" to "Protocol",
        "dbg_part_address" to "Address",
        "dbg_part_port" to "Port",
        "dbg_part_endpoint" to "Endpoint",
        "dbg_part_uuid" to "UUID",
        "dbg_part_password" to "Password",
        "dbg_part_method" to "Encryption method",
        "dbg_part_encryption" to "Encryption",
        "dbg_part_flow" to "Flow",
        "dbg_part_alterid" to "AlterId",
        "dbg_part_network" to "Network",
        "dbg_part_security" to "Security",
        "dbg_part_sni" to "SNI",
        "dbg_part_alpn" to "ALPN",
        "dbg_part_fingerprint" to "Fingerprint",
        "dbg_part_publickey" to "Public key",
        "dbg_part_privatekey" to "Private key",
        "dbg_part_shortid" to "Short ID",
        "dbg_part_path" to "Path",
        "dbg_part_host" to "Host",
        "dbg_part_header" to "Header type",
        "dbg_part_service" to "Service name",
        "dbg_part_mode" to "Mode",
        "dbg_part_localaddr" to "Local address",
        "dbg_part_mtu" to "MTU",
        "dbg_part_reserved" to "Reserved",
        "dbg_part_hy_bw" to "Bandwidth",
        "dbg_part_obfs" to "Obfuscation",
        "dbg_part_aether_mode" to "Aether mode",
        "dbg_part_tor_base" to "Base config",
        "dbg_part_tor_route" to "Tor routing",
        "dbg_part_auth" to "Auth",
        "dbg_part_insecure" to "Allow insecure",
        "dbg_part_pin" to "Pinned certificate",
        "dbg_pin_mismatch" to "The server certificate changed, re-pin it in the config",
        "dbg_pin_unreachable" to "Could not read the certificate to compare",
        "dbg_part_probe" to "Reachability probe",
        "dbg_empty" to "Missing",
        "dbg_unknown" to "Unknown value",
        "dbg_bad_port" to "Out of range 1-65535",
        "dbg_addr_scheme" to "Contains a URL scheme",
        "dbg_addr_space" to "Contains whitespace",
        "dbg_bad_uuid" to "Not a valid UUID",
        "dbg_bad_key" to "Not valid base64",
        "dbg_key_length" to "Wrong key length",
        "dbg_vless_encryption" to "VMess cipher used on a VLESS config",
        "dbg_flow_needs_tls" to "Flow requires TLS or Reality",
        "dbg_flow_needs_tcp" to "Vision flow requires TCP",
        "dbg_alterid_legacy" to "Legacy, should be 0",
        "dbg_reality_no_ws" to "Reality does not support this network",
        "dbg_reality_vless" to "Reality is VLESS only",
        "dbg_shortid_hex" to "Not hexadecimal",
        "dbg_shortid_len" to "Must be even length, max 16",
        "dbg_path_slash" to "Must start with /",
        "dbg_path_unverified" to "Transport could not be verified",
        "dbg_path_default" to "Empty, defaults to /",
        "dbg_host_empty" to "Empty, server may reject",
        "dbg_sni_fallback" to "Empty, falls back to address",
        "dbg_alpn_unknown" to "Unrecognised ALPN",
        "dbg_fp_empty" to "Empty, defaults to chrome",
        "dbg_insecure_on" to "Certificate check disabled",
        "dbg_insecure_reality" to "Ignored by Reality",
        "dbg_hy_fingerprint" to "uTLS is ignored over QUIC",
        "dbg_hy_bw_zero" to "Not set, congestion control disabled",
        "dbg_obfs_no_password" to "Obfuscation set without a password",
        "dbg_wg_reserved" to "Must be three values 0-255",
        "dbg_mtu_range" to "Outside 576-1500",
        "dbg_udp_probe" to "Not TCP, cannot be probed",
        "dbg_tor_local" to "Routed through the local Tor port",
        "dbg_aether_local" to "Handled by the Aether process",
        "dbg_tor_no_base" to "No base config, Tor runs direct",
        "shop_soon" to "Ghajarvpn Store",
        "shop_soon_sub" to "Buy and activate a service inside the app",
        "settings" to "Settings",
        "app_title" to "Ghajarvpn",
        "appearance" to "Appearance",
        "choose_server" to "Choose server",
        "add_config_title" to "Add config",
        "data_usage" to "Data usage",
        "selected_server" to "Selected server",
        "tap_choose" to "Tap to choose a server",
        "connect" to "Connect",
        "connecting_cancel" to "Connecting…  (tap to cancel)",
        "finding_fastest" to "Finding the fastest server",
        "allow_insecure" to "Allow insecure TLS",
        "allow_insecure_sub" to "Trust this server\u2019s certificate even if it does not match the SNI. The certificate is pinned when you turn this on.",
        "pin_fetching" to "Reading the server certificate\u2026",
        "pin_ready" to "Certificate pinned, this server is trusted",
        "pin_failed" to "Could not read the certificate, the server did not answer",
        "core_log_level" to "Xray log level",
        "core_log_level_sub" to "Higher levels write more engine detail to Logcat. Applies from the next connection.",
        "disconnect" to "Disconnect",
        "real_delay" to "Ping",
        "speed_test" to "Speed test",
        "testing" to "Testing…",
        "delay_failed" to "Timeout",
        "speed_failed" to "Speed: failed",
        "status_disconnected" to "Disconnected",
        "conn_disconnected" to "Disconnected",
        "conn_connected_for" to "Connected for %s",
        "conn_no_data" to "No data, check debugger tool",
        "status_connecting" to "Connecting…",
        "status_connected" to "Connected",
        "status_error" to "Error",
        "paste_links" to "Paste one or many links (one per line)",
        "add" to "Add",
        "paste_clipboard" to "Paste from clipboard",
        "add_manually" to "Add manually",
        "add_warp" to "Add WARP",
        "add_server" to "Add a server",
        "free_projects" to "Free projects",
        "import_from_file" to "Import from file",
        "legacy_warp" to "Legacy WARP",
        "proj_warp_desc" to "Cloudflare WARP over WireGuard. Free and no sign-up, but classic WARP is blocked in Iran \u2014 use Aether instead there.",
        "proj_more_soon" to "More free projects are on the way.",
        "proj_free" to "Free Configs",
        "proj_free_desc" to "Free configurations published by @Ghajarvpn. An empty channel shows no servers; no other source is substituted.",
        "proj_free_testing" to "Testing %d of %d, %d alive",
        "proj_free_working" to "Testing…",
        "proj_free_added" to "%d working configs added",
        "proj_free_none" to "None of the configs answered, try again later",
        "proj_free_unreachable" to "Could not reach the channel. Connect first, then refresh.",
        "proj_free_nocfg" to "No usable configs in the latest messages",
        "proj_aether" to "Aether",
        "proj_aether_title" to "Aether tunnel",
        "proj_aether_desc" to "MASQUE, WireGuard and nested WireGuard tunnels with automatic endpoint discovery.",
        "proj_aether_h2" to "Use HTTP/2",
        "proj_aether_h2_sub" to "Turn on when the network blocks or throttles UDP",
        "proj_aether_added" to "Aether added to your servers",
        "proj_tor_desc" to "The Tor anonymity network, with a choice of exit country. Slow but very resilient.",
        "proj_tor_missing" to "Tor engine is not bundled in this build",
        "proj_tor_added" to "Tor added",
        "tor_auto" to "Automatic",
        "tor_nodes" to "Tor nodes",
        "tor_nodes_intro" to "Pick one or more exit countries. Each adds its own Tor entry to your server list.",
        "tor_exit_country" to "Exit country",
        "tor_through_vpn" to "Route Tor through the tunnel",
        "tor_through_vpn_sub" to "Connects to Tor via your server instead of directly",
        "tor_add_auto" to "Add automatic exit",
        "tor_base_is" to "Tunnels through: %s",
        "tor_base_none" to "Select a working server first",
        "tor_add_n" to "Add %s nodes",
        "proj_aether_missing" to "Aether engine is not bundled in this build",
        "warp_added" to "WARP added",
        "warp_failed" to "WARP sign-up failed",
        "scan_warp" to "Scan Cloudflare IPs",
        "scan_title" to "Cloudflare IP scanner",
        "scan_sub" to "Find clean Cloudflare edge IPs that work here",
        "scan_intro" to "Samples Cloudflare's IP ranges and keeps the ones reachable from your network, ranked by latency. Tap an IP to copy it — use it as a clean IP for Cloudflare-fronted servers.",
        "scan_count" to "How many IPs to scan",
        "scan_start" to "Start scan",
        "scanning" to "Scanning…",
        "scan_done" to "%d clean IPs found",
        "scan_none" to "No reachable IPs found — scan again",
        "copy_all" to "Copy all",
        "copied" to "Copied",
        "copied_all" to "All IPs copied",
        "tools" to "Tools",
        "test_all" to "Test all",
        "test_completed" to "Test completed",
        "adding" to "Adding…",
        "added_configs" to "Added %d config(s)",
        "added_sub" to "Added a sub with %d configs",
        "clipboard_empty" to "Clipboard is empty",
        "pasted" to "Pasted from clipboard",
        "manual_configs" to "Manual configs",
        "refresh" to "Refresh",
        "copy" to "Copy",
        "ip_secured" to "Secured",
        "ip_exposed" to "Exposed",
        "hy_obfs" to "Obfuscation password (optional)",
        "hy_up" to "Up Mbps",
        "hy_down" to "Down Mbps",
        "remove" to "Remove",
        "delete" to "Delete",
        "edit" to "Edit",
        "share" to "Share",
        "share_clipboard" to "Share to clipboard",
        "share_app" to "Share to app",
        "share_file" to "Share as file",
        "show" to "Show",
        "export_title" to "Export config",
        "export_title_multi" to "Export configs",
        "export_file_name" to "File name",
        "export_password" to "Password (optional)",
        "export_password_hint" to "Leave empty for no password",
        "export_encrypted_note" to "Files are encrypted with AES-256 and can only be opened inside Ghajarvpn.",
        "export_locked_note" to "Imported configs are protected: their details can't be viewed or edited, but you can rename them.",
        "export_lock_details" to "Protect config details",
        "export_unlocked_note" to "Details will be visible and editable after import.",
        "export_continue" to "Choose where to share",
        "export_count" to "%d configs will be exported",
        "import_title" to "Import config file",
        "import_password" to "Enter file password",
        "import_wrong_password" to "Wrong password",
        "import_needs_password" to "This file is password protected",
        "import_bad_file" to "This file is invalid or damaged",
        "import_foreign_app" to "This file was made by a different build of Ghajarvpn",
        "import_success" to "%d configs imported",
        "import_open" to "Open",
        "import_button" to "Import",
        "locked_config" to "Protected config",
        "locked_note" to "This config is protected. You can only change its name.",
        "selected" to "selected",
        "delete_selected_q" to "Delete the selected configs?",
        "copied" to "Copied to clipboard",
        "edit_config_title" to "Edit config",
        "edit_sub_name" to "Edit name",
        "service_name" to "gRPC service name",
        "mode" to "Mode",
        "alpn" to "ALPN (comma-separated)",
        "fingerprint" to "Fingerprint",
        "xray_logs" to "Logcat",
        "xray_logs_sub" to "View the engine’s runtime output",
        "clear" to "Clear",
        "no_logs" to "No logs yet",
        "stab_title" to "Internet Quality Test",
        "stab_sub" to "Speed, ping, jitter and quality rating",
        "stab_start" to "Start test",
        "stab_stopping" to "Stopping…",
        "stab_ping" to "Ping",
        "stab_dl_ping" to "Download ping",
        "stab_ul_ping" to "Upload ping",
        "stab_jitter" to "Jitter",
        "stab_idle_latency" to "Idle latency",
        "stab_dl_latency" to "Download latency",
        "stab_ul_latency" to "Upload latency",
        "stab_direct_checking" to "Checking direct network\u2026",
        "stab_direct_stable" to "Direct network is stable",
        "stab_direct_unstable" to "Direct network is unstable",
        "stab_direct_offline" to "Internet connection is off",
        "stab_last_test" to "Last test:",
        "stab_quality" to "Quality",
        "stab_q_excellent" to "Excellent",
        "stab_q_good" to "Good",
        "stab_q_fair" to "Fair",
        "stab_q_poor" to "Poor",
        "stab_gaming" to "Gaming",
        "stab_browsing" to "Web browsing",
        "stab_streaming" to "Streaming",
        "stab_calling" to "Video calling",
        "stab_through_tunnel" to "Testing through the tunnel",
        "stab_direct" to "Testing your direct connection",
        "stab_failed" to "Test failed — check your connection",
        "stab_testing_server" to "Testing server:",
        "default_order" to "Default order",
        "fastest_first" to "Fastest first",
        "routing" to "Routing",
        "split_title" to "Split routing (Iran direct)",
        "split_sub" to "Iranian sites bypass the tunnel and connect directly.",
        "fragment_title" to "Fragment (anti-DPI)",
        "fragment_sub" to "Splits the TLS handshake to evade SNI filtering. Try it if a server won't connect.",
        "sniffing_title" to "Turn on Sniffing",
        "sniffing_type" to "Sniffing type",
        "sniffing_sub" to "Connects using the domain detected from traffic instead of the raw IP. Can help some servers connect correctly.",
        "kill_switch_title" to "Kill switch",
        "mux_title" to "Mux (multiplexing)",
        "mux_sub" to "Sends multiple connections through one stream. Can help on restrictive networks, but may reduce speed. Leave off with Reality/Vision.",
        "mux_concurrency" to "Max concurrent streams",
        "kill_switch_sub" to "Blocks all internet if the VPN drops unexpectedly, so your traffic never leaks. Tap disconnect to restore.",
        "always_on_title" to "Enable system lockdown",
        "always_on_sub" to "For a fully leak-proof kill switch, turn on \"Always-on VPN\" and \"Block connections without VPN\" for Ghajarvpn in system settings.",
        "globe_style_title" to "Globe style",
        "globe_style_filled" to "Filled",
        "globe_style_dots" to "Dots",
        "theme_settings" to "Theme settings",
        "theme_settings_sub" to "Appearance, colors and globe style",
        "theme_mode" to "Theme",
        "theme_light" to "Light",
        "theme_dark" to "Dark",
        "theme_amoled" to "AMOLED black",
        "theme_system" to "Follow system",
        "takes_effect" to "Changes take effect on the next connection.",
        "language" to "Language",
        "about" to "About",
        "about_sub" to "Version, developer & privacy policy",
        "app_version" to "App version",
        "about_tagline" to "Royal privacy, stable connection, native service management",
        "xray_version" to "Xray core",
        "telegram_support" to "Telegram channel",
        "privacy_policy" to "Privacy Policy",
        "developer" to "Developer",
        "source_code" to "Source code",
        "check_updates" to "Check for updates",
        "checking_updates" to "Checking…",
        "up_to_date" to "You're on the latest version",
        "update_available" to "Update available: %s",
        "update_failed" to "Couldn't check — try again",
        "update_now" to "Update",
        "later" to "Later",
        "auto_refresh" to "Auto-refresh subscriptions",
        "auto_refresh_off" to "Off",
        "every_hour" to "Every %s hour",
        "every_hours" to "Every %s hours",
        "all_time_total" to "All-time total",
        "tap_ranges" to "Tap for ranges and custom dates  ›",
        "range" to "Range",
        "today" to "Today",
        "range_7d" to "7d",
        "range_30d" to "30d",
        "custom_range" to "Custom range",
        "from" to "From",
        "to" to "To",
        "from_hour" to "From hour",
        "to_hour" to "To hour",
        "custom_hint" to "Up to 2 days shows hourly detail; longer shows daily. Hourly history is kept ~30 days.",
        "download" to "Download",
        "upload" to "Upload",
        "total" to "Total",
        "no_data_range" to "No data for this range.",
        "tunnel_only" to "Counts only traffic sent through the tunnel.",
        "peak_per_bar" to "Peak %s per bar",
        "name_optional" to "Name (optional)",
        "protocol" to "Protocol",
        "address" to "Address",
        "port" to "Port",
        "uuid" to "UUID",
        "password" to "Password",
        "ikev2_user" to "Username",
        "ws_title" to "Windscribe",
        "ws_intro" to "Server list is loaded from Windscribe automatically. Enter your IKEv2 credentials, pick the servers you want, and each is added with its IP as address and hostname as server identity.",
        "ws_credentials" to "IKEv2 credentials",
        "ws_locations" to "Server locations",
        "ws_loading" to "Loading server list\u2026",
        "ws_fetch_failed" to "Could not load the server list, check your connection",
        "ws_need_host" to "Paste at least one hostname",
        "ws_creds_hint" to "Get these from windscribe.com/myaccount under Config Generators \u2192 IKEv2. They are not your website login.",
        "ws_need_creds" to "Enter your username and password first",
        "ws_add_n" to "Add %s configs",
        "ws_added" to "%d configs added",
        "ikev2_remote_id" to "Server identity (hostname)",
        "dbg_ikev2_nodebug" to "IKEv2 configs cannot be debugged",
        "ike_err_auth" to "Authentication failed, check username and password",
        "ike_err_peer" to "Server authentication failed",
        "ike_err_lookup" to "Server address could not be resolved",
        "ike_err_unreachable" to "Server is not reachable",
        "ike_err_password" to "Password is missing",
        "ike_err_cert" to "Certificate is unavailable",
        "ike_err_generic" to "Connection failed",
        "ikev2_note" to "If the domain is DNS-poisoned on your network, put the server IP in Address and keep the hostname as Server identity. IKEv2 runs on its own engine, so per-app proxy, split routing and the debugger do not apply.",
        "ikev2_bad_config" to "IKEv2 config is invalid",
        "enc_method" to "Encryption method",
        "flow_optional" to "Flow (optional)",
        "network" to "Network",
        "security" to "Security",
        "sni" to "SNI / server name",
        "public_key" to "Public key (pbk)",
        "short_id" to "Short ID (sid)",
        "ws_path" to "WS path",
        "ws_host" to "WS host header",
        "cancel" to "Cancel",
        "save" to "Save",
        "err_address" to "Address is required",
        "err_port" to "Port must be 1–65535",
        "err_uuid" to "UUID is required",
        "err_password" to "Password is required",
        "fetching_sub" to "Fetching subscription…",
        "no_configs" to "No configs found",
        "fetch_failed" to "Fetch failed",
        "sub_err_http" to "Server returned error %s",
        "sub_err_empty" to "The link returned nothing",
        "sub_err_notconfig" to "That link is not a config list — check the URL",
        "sub_err_clash" to "This is a Clash / sing-box subscription, which isn't supported",
        "parse_none" to "Couldn't parse any links",
        "left" to "left",
        "of" to "of",
        "expires_in" to "expires in",
        "unit_b" to "B",
        "unit_kb" to "KB",
        "unit_mb" to "MB",
        "unit_gb" to "GB",
        "unit_ms" to "ms",
        "unit_mbps" to "Mbps",
        "unit_per_sec" to "/s",
        "unit_days" to "d",
        "welcome_tagline" to "Royal security, Fast connection",
        "welcome_dev" to "Ghajarvpn",
        "per_app" to "Per-app proxy",
        "per_app_sub" to "Choose which apps use the VPN",
        "per_app_mode" to "Mode",
        "per_app_off" to "Off",
        "per_app_allow" to "Only select",
        "per_app_block" to "All except",
        "per_app_off_hint" to "Per-app routing is off — every app uses the VPN.",
        "per_app_empty_error" to "Select at least one installed app before connecting in Only selected mode.",
        "search_apps" to "Search apps",
        "search_servers" to "Search servers",
        "connection_settings" to "Connection Settings",
        "connection_settings_sub" to "Routing, kill switch and per-app proxy",
        "usage_by_config" to "Usage by server",
        "usage_direct" to "Direct (VPN off)",
        "via_vpn" to "Via VPN",
        "smart_connect" to "Smart connect",
        "advanced" to "Advanced",
        "adblock_title" to "Block ads and trackers",
        "adblock_always_title" to "Keep blocking when disconnected",
        "adblock_always_sub" to "Runs a local filter with no proxy, so traffic stays direct",
        "adblock_notif" to "Ad blocker",
        "fakedns_title" to "Fake DNS",
        "fakedns_sub" to "Gives each domain its own address so per-host rules always apply",
        "encdns_title" to "Encrypted DNS",
        "encdns_sub" to "Resolves names over DoH instead of plain DNS",
        "dns_leak_title" to "Strict DNS leak protection",
        "dns_leak_sub" to "When encrypted DNS is enabled, removes plain-DNS fallbacks. DNS remains inside the VPN route.",
        "ipv6_title" to "IPv6 handling",
        "ipv6_sub" to "IPv6 is always captured by Ghajar; block it safely or carry it through the tunnel.",
        "ipv6_block" to "Block (safe)",
        "ipv6_tunnel" to "Through VPN",
        "onion_title" to "Route .onion through Tor",
        "onion_sub" to "Opens onion addresses over Tor while everything else uses your server",
        "adblock_sub" to "Drops known ad and tracking domains inside the tunnel",
        "mixed_port" to "Mixed port",
        "mixed_port_sub" to "Local SOCKS/HTTP listen port",
        "smart_connect_sub" to "Tests every server each minute and switches to the fastest",
        "preferences" to "Preferences",
        "tools_sub" to "Adblocker, quality test, check host and smart connect",
        "netmon_title" to "Network Radar",
        "netmon_sub" to "Check which sites are down or blocked on your network",
        "chk_title" to "Check Host",
        "chk_sub" to "Check every address info and reachability.",
        "chk_intro" to "Check every address info and reachability.",
        "chk_host" to "Host or IP",
        "chk_ping" to "Ping",
        "chk_http" to "HTTP",
        "chk_tcp" to "TCP",
        "chk_start" to "Run check",
        "chk_running" to "Checking\u2026",
        "chk_failed" to "Could not reach check-host.net",
        "chk_info" to "Address info",
        "chk_ip" to "IP address",
        "chk_asn" to "ASN",
        "chk_org" to "ISP / Org",
        "chk_country" to "Country",
        "chk_region" to "Region",
        "chk_city" to "City",
        "chk_tz" to "Time zone",
        "netmon_intro" to "Opens a direct connection to each site through the current route.",
        "netmon_via_tunnel" to "Checking through the tunnel",
        "netmon_via_direct" to "Checking directly (VPN off)",
        "netmon_up" to "Reachable",
        "netmon_down" to "Not reachable",
        "netmon_summary" to "%s of %s reachable",
        "netmon_testing" to "Checking %s/%s",
        "netmon_recheck" to "Check again",
        "netmon_sanctioned" to "Blocked (403)",
        "netcat_title" to "More categories",
        "netcat_sub" to "AI, social, gaming, trading, news and Iranian sites",
        "netcat_ai" to "AI",
        "netcat_news" to "News",
        "netcat_count" to "%s sites",
        "netcat_gaming" to "Gaming",
        "netcat_social" to "Social",
        "netcat_trading" to "Trading",
        "netcat_iranian" to "Iranian platforms",
        "preferences_sub" to "Theme, language and subscription refresh",
        "sort_alpha" to "Alphabetic",
        "sort_fastest" to "Fastest",
        "sort_added" to "Time added",
        "sort" to "Sort",
        "delete_all" to "Delete",
        "delete_manual_configs" to "Delete manual configs",
        "delete_everything" to "Delete everything",
        "delete_manual_q" to "Delete %s manually added configs? Subscriptions are kept.",
        "delete_everything_q" to "Delete all %s configs and every subscription? This cannot be undone.",
        "no_manual" to "No manually added configs",
        "delete_all_configs" to "Delete all configs",
        "delete_timed_out" to "Delete timed out",
        "delete_duplicates" to "Delete duplicates",
        "delete_duplicates_q" to "Delete %s duplicate configs? The first copy of each is kept.",
        "no_duplicates" to "No duplicate configs found",
        "delete_all_q" to "Delete all %s configs? This cannot be undone.",
        "delete_timeout_q" to "Delete %s timed out configs?",
        "delete_sub_q" to "Delete this subscription and all %s of its configs?",
        "no_timed_out" to "No timed out configs — run Test all first",
        "deleted_n" to "%s configs deleted",
        "qr_share" to "Share as QR",
        "qr_title" to "Scan to import",
        "qr_hint" to "Scan this code with another device to import the config",
        "qr_save" to "Save image",
        "qr_saved" to "QR image saved",
        "qr_too_long" to "Config is too long for a QR code",
        "scan_qr" to "Scan QR code",
        "scan_qr_hint" to "Point the camera at a config or subscription QR code",
        "camera_needed" to "Camera permission is needed to scan",
        "camera_grant" to "Grant permission",
        "qr_invalid" to "No config found in that QR code",
        "backup_title" to "Backup & restore",
        "backup_sub" to "Save or restore everything in one file",
        "backup_export" to "Create backup",
        "backup_import" to "Restore backup",
        "backup_note" to "A backup holds your servers, subscriptions and every setting. It is encrypted and only opens inside Ghajarvpn.",
        "backup_creating" to "Creating backup…",
        "backup_done" to "Backup saved",
        "backup_restored" to "Restored %s configs and %s subscriptions",
        "backup_restore_q" to "Restoring replaces all current servers, subscriptions and settings. Continue?",
        "backup_not_backup" to "That file is a shared config, not a backup",
        "backup_failed" to "Backup could not be created",
        "loading_apps" to "Loading apps…"
    )

    private val fa = mapOf(
        "connection" to "اتصال",
        "shop" to "فروشگاه",
        "ssh" to "SSH",
        "srv_checks" to "سمت سرور",
        "pnl_checks" to "سمت پنل",
        "pnl_kind" to "نوع پنل",
        "pnl_url" to "آدرس پنل",
        "pnl_user" to "نام کاربری پنل",
        "pnl_pass" to "رمز پنل",
        "pnl_run" to "بررسی پنل",
        "pnl_running" to "در حال بررسی…",
        "pnl_part_reach" to "آدرس پنل",
        "pnl_part_node" to "نود ورودی",
        "pnl_part_exit" to "نود خروجی",
        "pnl_part_host" to "تنظیمات هاست",
        "pnl_part_inbound" to "اینباند",
        "pnl_part_route" to "قانون مسیریابی",
        "pnl_part_outbound" to "اوتباند",
        "pnl_node_missing" to "هیچ نودی در این پنل این آدرس را ندارد",
        "pnl_node_down" to "پنل این نود را خراب گزارش می دهد",
        "pnl_host_missing" to "هاستی با این آدرس پیدا نشد",
        "pnl_host_disabled" to "این هاست در پنل غیرفعال است",
        "pnl_host_mismatch" to "کانفیگ با تنظیمات هاست همخوانی ندارد",
        "pnl_inbound_unknown" to "هاست تگ اینباند ندارد",
        "pnl_inbound_missing" to "اینباندی که هاست به آن اشاره می‌کند وجود ندارد",
        "pnl_inbound_mismatch" to "کانفیگ با اینباند همخوانی ندارد",
        "pnl_core_missing" to "هیچ هسته ای این اینباند را ندارد",
        "pnl_outbound_missing" to "قانون مسیریابی به اوتباندی اشاره می‌کند که وجود ندارد",
        "pnl_outbound_unknown" to "مقصد اوتباند مشخص نیست",
        "pnl_exit_missing" to "سرور خروجی در این پنل نود نیست",
        "pnl_part_login" to "ورود ادمین",
        "pnl_part_core" to "هسته به گزارش پنل",
        "pnl_part_uptime" to "مدت روشن بودن پنل",
        "pnl_no_url" to "ابتدا آدرس پنل را وارد کنید",
        "pnl_unreachable" to "پنل در این آدرس پاسخی نداد",
        "pnl_timeout" to "زمان تمام شد، پورت را بررسی کنید. پنل‌ها کمتر روی 443 هستند",
        "pnl_tls" to "TLS ناموفق بود، سرتیفیکت پنل معتبر نیست. آدرس http:// فقط روی شبکه قابل اعتماد، چون رمز را بدون رمزنگاری می‌فرستد.",
        "pnl_dns" to "این آدرس ریزالو نمی‌شود",
        "pnl_refused" to "اتصال رد شد، چیزی روی این پورت فعال نیست",
        "pnl_bad_login" to "پنل این مشخصات را نپذیرفت",
        "pnl_csrf" to "پنل ورود را رد کرد، آدرس و TLS را بررسی کنید",
        "pnl_core_down" to "پنل گزارش می‌دهد هسته در حال اجرا نیست",
        "pnl_core_error" to "پنل خطای هسته را شناسایی کرده",
        "pnl_unknown" to "قابل تشخیص نبود",
        "srv_via" to "بررسی از طریق SSH روی %s",
        "srv_host" to "اجرا روی",
        "srv_run" to "بررسی سرور",
        "srv_running" to "در حال بررسی…",
        "srv_part_listen" to "گوش دادن پورت",
        "srv_part_core" to "پروسه هسته",
        "srv_part_firewall" to "فایروال",
        "srv_part_cert" to "انقضای گواهی",
        "srv_part_log" to "خطاهای اخیر هسته",
        "srv_part_load" to "بار پردازشی",
        "srv_no_listen" to "چیزی روی این پورت فعال نیست",
        "srv_no_core" to "هیچ پروسه هسته‌ای در حال اجرا نیست",
        "srv_fw_no_rule" to "قانون فایروالی برای این پورت پیدا نشد",
        "srv_no_cert" to "برای این SNI گواهی ارائه نشد",
        "srv_load_high" to "بار سرور اشباع شده",
        "srv_load_critical" to "بار بسیار بیشتر از تعداد هسته‌هاست، سرور اورلود است",
        "srv_unknown" to "قابل تشخیص نبود",
        "ssh_add" to "افزودن سرور",
        "ssh_add_sub" to "یک سرور ذخیره کنید تا با SSH وصل شوید",
        "term_local" to "ترمینال لوکال",
        "term_local_sub" to "یک شل روی این دستگاه، داخل محیط برنامه",
        "term_running" to "شل در حال اجرا",
        "term_stopped" to "شل متوقف است",
        "ssh_state_off" to "قطع",
        "ssh_host_details" to "سرور",
        "ssh_credentials" to "مشخصات ورود",
        "ssh_edit" to "ویرایش سرور",
        "ssh_empty" to "هنوز سروری اضافه نشده",
        "ssh_empty_sub" to "یک سرور اضافه کنید تا با SSH به آن متصل شوید",
        "ssh_label" to "نام (اختیاری)",
        "ssh_address" to "هاست یا آی‌پی",
        "ssh_port" to "پورت",
        "ssh_username" to "نام کاربری",
        "ssh_password" to "رمز عبور",
        "ssh_direct" to "اتصال مستقیم",
        "ssh_direct_sub" to "برای این سرور به طور مستقیم متصل می شود.",
        "ssh_connect" to "اتصال",
        "ssh_disconnect" to "قطع اتصال",
        "ssh_open_shell" to "شل",
        "sftp" to "فایل‌ها",
        "sftp_empty" to "این پوشه خالی است",
        "sftp_failed" to "سرور این عملیات را رد کرد",
        "sftp_upload" to "آپلود",
        "sftp_new_folder" to "پوشه جدید",
        "sftp_folder_name" to "نام پوشه",
        "sftp_downloading" to "در حال دانلود…",
        "sftp_uploading" to "در حال آپلود…",
        "sftp_delete_title" to "حذف",
        "sftp_delete_q" to "%s از سرور حذف شود؟ این کار قابل بازگشت نیست.",
        "ssh_connecting" to "در حال اتصال…",
        "ssh_connected" to "متصل",
        "ssh_via_tunnel" to "از طریق تونل",
        "ssh_via_direct" to "اتصال مستقیم",
        "ssh_delete_title" to "حذف سرور",
        "ssh_delete_q" to "%s حذف شود؟ این کار قابل بازگشت نیست.",
        "ssh_err_auth" to "احراز هویت ناموفق بود، نام کاربری و رمز را بررسی کنید",
        "ssh_err_host" to "آدرس سرور ریزالو نشد",
        "ssh_err_timeout" to "زمان اتصال تمام شد",
        "ssh_err_refused" to "اتصال رد شد، پورت را بررسی کنید",
        "ssh_err_proxy" to "دسترسی به تونل وجود نداشت، VPN را وصل کنید یا مستقیم بزنید",
        "ssh_err_no_user" to "نام کاربری الزامی است",
        "ssh_err_generic" to "اتصال ناموفق بود",
        "chain_through" to "اتصال از طریق",
        "chain_hint" to "این کانفیگ از طریق کانفیگ دیگری متصل می‌شود، تونل داخل تونل",
        "chain_none" to "مستقیم",
        "chain_carrier" to "کانفیگ حامل",
        "home" to "خانه",
        "debugger" to "دیباگر",
        "debugger_title" to "دیباگر کانفیگ",
        "dbg_offline" to "آفلاین",
        "dbg_undetermined" to "قابل تشخیص نبود",
        "dbg_part_remote" to "دسترسی از بیرون",
        "dbg_part_core" to "هندشیک پروتکل",
        "dbg_local_udp" to "UDP از این دستگاه قابل تست نیست",
        "dbg_handshake_failed" to "هندشیک رد شد، مشخصات کانفیگ و تنظیمات ترنسپورت را بررسی کنید",
        "dbg_reality_refused" to "سرور هندشیک را رد کرد",
        "dbg_no_traffic" to "اتصال برقرار است اما ترافیکی عبور نمی‌کند",
        "dbg_part_quota" to "اشتراک",
        "dbg_sub_expired" to "اشتراک منقضی شده است",
        "dbg_sub_exhausted" to "حجم اشتراک تمام شده است",
        "dbg_sub_low" to "کمتر از ۱۰ درصد حجم باقی مانده",
        "dbg_sub_ending" to "کمتر از ۳ روز تا انقضا",
        "dbg_blocked" to "مسدود",
        "dbg_part_dns" to "DNS",
        "dbg_part_domain" to "دامنه",
        "dbg_part_exposure" to "لو رفتن VPN",
        "dbg_vpn_exposed" to "IP به عنوان VPN شناسایی شده است",
        "dbg_exit_blocked" to "IP خروجی از شبکه شما مسدود است",
        "dbg_part_tcp" to "هندشیک TCP",
        "dbg_part_tls" to "هندشیک TLS",
        "dbg_dns_fail" to "آدرس ریزالو نمی‌شود",
        "dbg_domain_filtered" to "دامنه توسط شبکه شما فیلتر شده است",
        "dbg_no_internet" to "این شبکه اینترنت ندارد",
        "dbg_addr_mismatch" to "آدرس آنلاین است اما چیزی روی این پورت گوش نمی‌دهد",
        "dbg_addr_offline" to "آدرس آفلاین است",
        "dbg_port_blocked" to "پورت توسط شبکه شما مسدود است",
        "dbg_ip_blocked" to "IP توسط شبکه شما مسدود است",
        "dbg_tls_cert" to "گواهی با SNI همخوانی ندارد، allow insecure را فعال کنید",
        "dbg_tls_cert_insecure" to "سرتیفیکت حتی با allow insecure رد شد",
        "dbg_sni_blocked" to "SNI مسدود است، هندشیک ریست شد",
        "dbg_sni_mismatch" to "سرتیفیکت رد شد، احتمالاً SNI خراب است",
        "dbg_sni_no_resolve" to "دامنه SNI وجود ندارد",
        "dbg_sni_filtered" to "دامنه SNI در شبکه شما فیلتر است",
        "dbg_sni_no_tls13" to "دامنه SNI از TLS 1.3 پشتیبانی نمی‌کند",
        "dbg_sni_unreachable" to "دامنه SNI در دسترس نیست",
        "dbg_sni_timeout" to "SNI در دسترس نیست",
        "dbg_host_blocked" to "دامنه هاست در دسترس نیست",
        "dbg_info" to "جزئیات اتصال",
        "dbg_part_transport" to "متود",
        "dbg_part_entry" to "ورودی",
        "dbg_part_ip" to "خروجی",
        "dbg_connecting" to "در حال اتصال به این کانفیگ",
        "dbg_part_iptype" to "نوع IP",
        "dbg_part_risk" to "اعتبار",
        "dbg_exit_offline" to "برای دیدن IP خروجی متصل شوید",
        "dbg_part_flags" to "شناسایی شده به عنوان",
        "dbg_rep_flagged" to "محدوده شناخته‌شده VPN، پراکسی یا Tor",
        "dbg_rep_unavailable" to "در دسترس نیست",
        "dbg_state" to "وضعیت اتصال",
        "dbg_healthy" to "سالم",
        "dbg_timeout" to "تایم اوت",
        "dbg_broken" to "خراب",
        "dbg_testing" to "در حال بررسی",
        "dbg_ping" to "پینگ",
        "dbg_recheck" to "بررسی دوباره",
        "dbg_no_config" to "کانفیگی انتخاب نشده است. اول یک سرور انتخاب کنید.",
        "dbg_client_checks" to "سمت کلاینت",
        "dbg_all_ok" to "همه بخش‌ها معتبرند",
        "dbg_issues" to "%s خراب، %s هشدار",
        "dbg_part_protocol" to "پروتکل",
        "dbg_part_address" to "آدرس",
        "dbg_part_port" to "پورت",
        "dbg_part_endpoint" to "مقصد",
        "dbg_part_uuid" to "UUID",
        "dbg_part_password" to "رمز عبور",
        "dbg_part_method" to "روش رمزنگاری",
        "dbg_part_encryption" to "رمزنگاری",
        "dbg_part_flow" to "Flow",
        "dbg_part_alterid" to "AlterId",
        "dbg_part_network" to "شبکه",
        "dbg_part_security" to "امنیت",
        "dbg_part_sni" to "SNI",
        "dbg_part_alpn" to "ALPN",
        "dbg_part_fingerprint" to "اثر انگشت",
        "dbg_part_publickey" to "کلید عمومی",
        "dbg_part_privatekey" to "کلید خصوصی",
        "dbg_part_shortid" to "Short ID",
        "dbg_part_path" to "مسیر",
        "dbg_part_host" to "هاست",
        "dbg_part_header" to "نوع هدر",
        "dbg_part_service" to "نام سرویس",
        "dbg_part_mode" to "حالت",
        "dbg_part_localaddr" to "آدرس لوکال",
        "dbg_part_mtu" to "MTU",
        "dbg_part_reserved" to "Reserved",
        "dbg_part_hy_bw" to "پهنای باند",
        "dbg_part_obfs" to "مبهم‌سازی",
        "dbg_part_aether_mode" to "حالت Aether",
        "dbg_part_tor_base" to "کانفیگ پایه",
        "dbg_part_tor_route" to "مسیر Tor",
        "dbg_part_auth" to "احراز هویت",
        "dbg_part_insecure" to "Allow insecure",
        "dbg_part_pin" to "Pinned certificate",
        "dbg_pin_mismatch" to "The server certificate changed, re-pin it in the config",
        "dbg_pin_unreachable" to "Could not read the certificate to compare",
        "dbg_part_probe" to "تست دسترسی",
        "dbg_empty" to "خالی است",
        "dbg_unknown" to "مقدار ناشناخته",
        "dbg_bad_port" to "خارج از بازه ۱ تا ۶۵۵۳۵",
        "dbg_addr_scheme" to "شامل پیشوند آدرس است",
        "dbg_addr_space" to "شامل فاصله است",
        "dbg_bad_uuid" to "uuid معتبر نیست",
        "dbg_bad_key" to "base64 معتبر نیست",
        "dbg_key_length" to "طول کلید نادرست است",
        "dbg_vless_encryption" to "رمز VMess روی کانفیگ VLESS",
        "dbg_flow_needs_tls" to "Flow به TLS یا Reality نیاز دارد",
        "dbg_flow_needs_tcp" to "Vision به TCP نیاز دارد",
        "dbg_alterid_legacy" to "قدیمی، باید ۰ باشد",
        "dbg_reality_no_ws" to "Reality این شبکه را پشتیبانی نمی‌کند",
        "dbg_reality_vless" to "Reality فقط با VLESS کار می‌کند",
        "dbg_shortid_hex" to "هگزادسیمال نیست",
        "dbg_shortid_len" to "طول باید زوج و حداکثر ۱۶ باشد",
        "dbg_path_slash" to "باید با / شروع شود",
        "dbg_path_unverified" to "ترنسپورت قابل تأیید نبود",
        "dbg_path_default" to "خالی، پیش‌فرض /",
        "dbg_host_empty" to "خالی، ممکن است رد شود",
        "dbg_sni_fallback" to "خالی، از آدرس استفاده می‌شود",
        "dbg_alpn_unknown" to "ALPN ناشناخته",
        "dbg_fp_empty" to "خالی، پیش‌فرض chrome",
        "dbg_insecure_on" to "بررسی سرتیفیکت غیرفعال است",
        "dbg_insecure_reality" to "در Reality نادیده گرفته می‌شود",
        "dbg_hy_fingerprint" to "uTLS روی QUIC بی‌اثر است",
        "dbg_hy_bw_zero" to "تنظیم نشده است",
        "dbg_obfs_no_password" to "مبهم‌سازی بدون رمز است",
        "dbg_wg_reserved" to "باید سه مقدار ۰ تا ۲۵۵ باشد",
        "dbg_mtu_range" to "خارج از ۵۷۶ تا ۱۵۰۰",
        "dbg_udp_probe" to "TCP نیست، غیر قابل آزمایش",
        "dbg_tor_local" to "از پورت لوکال Tor عبور می‌کند",
        "dbg_aether_local" to "توسط هسته Aether تنظیم می‌شود",
        "dbg_tor_no_base" to "کانفیگ پایه ندارد، Tor مستقیم است",
        "shop_soon" to "فروشگاه قاجار وی پی ان",
        "shop_soon_sub" to "خرید و فعال‌سازی سرویس از داخل برنامه",
        "settings" to "تنظیمات",
        "app_title" to "قاجار وی پی ان",
        "choose_server" to "انتخاب سرور",
        "add_config_title" to "افزودن کانفیگ",
        "data_usage" to "مصرف داده",
        "selected_server" to "سرور انتخاب‌شده",
        "tap_choose" to "برای انتخاب سرور ضربه بزنید",
        "connect" to "اتصال",
        "connecting_cancel" to "در حال اتصال…  (برای لغو ضربه بزنید)",
        "finding_fastest" to "در حال یافتن سریع‌ترین سرور",
        "allow_insecure" to "مجاز بودن TLS ناامن",
        "allow_insecure_sub" to "گواهی این سرور را حتی اگر با SNI همخوانی ندارد معتبر بدان. با روشن کردن، گواهی پین می‌شود.",
        "pin_fetching" to "در حال خواندن سرتیفیکت سرور…",
        "pin_ready" to "سرتیفیکت پین شد، این سرور معتبر است",
        "pin_failed" to "سرتیفیکت خوانده نشد، سرور پاسخی نداد",
        "core_log_level" to "سطح لاگ Xray",
        "core_log_level_sub" to "سطح بالاتر جزئیات بیشتری از موتور را در لاگ‌کت می‌نویسد. از اتصال بعدی اعمال می‌شود.",
        "disconnect" to "قطع اتصال",
        "real_delay" to "پینگ",
        "speed_test" to "تست سرعت",
        "testing" to "در حال تست…",
        "delay_failed" to "تایم‌اوت",
        "speed_failed" to "سرعت: ناموفق",
        "status_disconnected" to "قطع",
        "conn_disconnected" to "قطع",
        "conn_connected_for" to "متصل به مدت %s",
        "conn_no_data" to "داده‌ای رد و بدل نمی‌شود، دیباگر را ببینید",
        "status_connecting" to "در حال اتصال…",
        "status_connected" to "متصل",
        "status_error" to "خطا",
        "paste_links" to "یک یا چند لینک را وارد کنید (هر کدام در یک خط)",
        "add" to "افزودن",
        "paste_clipboard" to "وارد کردن از کلیپ‌بورد",
        "add_manually" to "افزودن دستی",
        "add_warp" to "افزودن WARP",
        "add_server" to "افزودن سرور",
        "free_projects" to "پروژه‌های رایگان",
        "import_from_file" to "ورود از فایل",
        "legacy_warp" to "WARP کلاسیک",
        "proj_warp_desc" to "کلودفلر WARP روی WireGuard. رایگان و بدون ثبت‌نام توسط اپ انجام می شود، اما WARP کلاسیک در ایران مسدود است — در ایران از Aether استفاده کنید.",
        "proj_more_soon" to "پروژه‌های رایگان بیشتری به‌زودی اضافه می‌شود.",
        "proj_free" to "کانفیگ‌های رایگان",
        "proj_free_desc" to "کانفیگ‌های رایگان منتشرشده در @Ghajarvpn؛ اگر کانال کانفیگی نداشته باشد، منبع دیگری جایگزین نمی‌شود.",
        "proj_free_testing" to "تست %d از %d، %d سالم",
        "proj_free_working" to "در حال تست…",
        "proj_free_added" to "%d کانفیگ سالم اضافه شد",
        "proj_free_none" to "هیچ کانفیگی پاسخ نداد، بعداً دوباره امتحان کنید",
        "proj_free_unreachable" to "دسترسی به کانال وجود نداشت. اول به وی پی ان متصل شوید و دوباره بزنید.",
        "proj_free_nocfg" to "در پیام‌های اخیر کانفیگ قابل استفاده‌ای نبود",
        "proj_aether" to "اتر",
        "proj_aether_title" to "تونل اتر",
        "proj_aether_desc" to "تونل MASQUE، وایرگارد و وایرگارد تودرتو با پیدا کردن خودکار مسیر.",
        "proj_aether_h2" to "استفاده از HTTP/2",
        "proj_aether_h2_sub" to "مخصوص مواقعی که شبکه UDP را مسدود یا کند کرده",
        "proj_aether_added" to "Aether به سرورهای شما اضافه شد",
        "proj_tor_desc" to "شبکه ناشناس تور با امکان انتخاب کشور خروجی. کند اما بسیار مقاوم.",
        "proj_tor_missing" to "انجین تور در این نسخه موجود نیست",
        "proj_tor_added" to "تور اضافه شد",
        "tor_auto" to "خودکار",
        "tor_nodes" to "گره‌های تور",
        "tor_nodes_intro" to "یک یا چند کشور خروجی انتخاب کنید. برای هرکدام یک ورودی تور به فهرست سرورها اضافه می‌شود.",
        "tor_exit_country" to "کشور خروجی",
        "tor_through_vpn" to "عبور تور از تونل",
        "tor_through_vpn_sub" to "به‌جای اتصال مستقیم، از طریق سرور شما به تور وصل می‌شود",
        "tor_add_auto" to "افزودن خروجی خودکار",
        "tor_base_is" to "از طریق: %s",
        "tor_base_none" to "ابتدا یک سرور سالم انتخاب کنید",
        "tor_add_n" to "افزودن %s گره",
        "proj_aether_missing" to "موتور اتر در این نسخه قرار داده نشده است",
        "warp_added" to "WARP اضافه شد",
        "warp_failed" to "ثبت WARP ناموفق بود",
        "scan_warp" to "اسکن آی‌پی‌های کلودفلر",
        "scan_title" to "اسکنر آی‌پی کلودفلر",
        "scan_sub" to "پیدا کردن آی‌پی‌های تمیز کلودفلر که اینجا کار می‌کنند",
        "scan_intro" to "از رنج آی‌پی های کلودفلر نمونه‌برداری می‌کند و آن‌هایی را که از شبکه شما در دسترس‌اند بر اساس پینگ مرتب می‌کند. برای کپی روی آی‌پی بزنید — به‌عنوان آی‌پی تمیز برای سرورهای پشت کلودفلر استفاده کنید.",
        "scan_count" to "چند آی‌پی اسکن شود",
        "scan_start" to "شروع اسکن",
        "scanning" to "در حال اسکن…",
        "scan_done" to "%d آی‌پی سالم پیدا شد",
        "scan_none" to "آی‌پی در دسترس پیدا نشد — دوباره اسکن کنید",
        "copy_all" to "کپی همه",
        "copied" to "کپی شد",
        "copied_all" to "همه آی‌پی‌ها کپی شد",
        "tools" to "ابزارها",
        "test_all" to "تست همه",
        "test_completed" to "تست کامل شد",
        "adding" to "در حال افزودن…",
        "added_configs" to "%d کانفیگ افزوده شد",
        "added_sub" to "ساب با %d کانفیگ افزوده شد",
        "clipboard_empty" to "کلیپ‌بورد خالی است",
        "pasted" to "از کلیپ‌بورد پیست شد",
        "manual_configs" to "کانفیگ‌های دستی",
        "refresh" to "بروزرسانی",
        "copy" to "کپی",
        "ip_secured" to "امن",
        "ip_exposed" to "محافظت‌نشده",
        "hy_obfs" to "رمز مبهم‌سازی (اختیاری)",
        "hy_up" to "آپلود Mbps",
        "hy_down" to "دانلود Mbps",
        "remove" to "حذف",
        "delete" to "حذف",
        "edit" to "ویرایش",
        "share" to "اشتراک‌گذاری",
        "share_clipboard" to "اشتراک در کلیپ‌بورد",
        "share_app" to "اشتراک با برنامه",
        "share_file" to "اشتراک به‌صورت فایل",
        "show" to "نمایش",
        "export_title" to "خروجی کانفیگ",
        "export_title_multi" to "خروجی کانفیگ‌ها",
        "export_file_name" to "نام فایل",
        "export_password" to "رمز (اختیاری)",
        "export_password_hint" to "برای بدون رمز، خالی بگذارید",
        "export_encrypted_note" to "فایل‌ها با AES-256 رمزنگاری می‌شوند و فقط داخل قاجار وی پی ان باز می‌شوند.",
        "export_locked_note" to "کانفیگ‌های واردشده محافظت‌شده‌اند: جزئیاتشان قابل مشاهده یا ویرایش نیست، اما می‌توانید نامشان را تغییر دهید.",
        "export_lock_details" to "محافظت از جزئیات کانفیگ",
        "export_unlocked_note" to "جزئیات بعد از وارد کردن قابل دیدن و ویرایش خواهد بود.",
        "export_continue" to "انتخاب مقصد اشتراک",
        "export_count" to "%d کانفیگ خروجی گرفته می‌شود",
        "import_title" to "ورود فایل کانفیگ",
        "import_password" to "رمز فایل را وارد کنید",
        "import_wrong_password" to "رمز اشتباه است",
        "import_needs_password" to "این فایل رمز دارد",
        "import_bad_file" to "این فایل نامعتبر یا خراب است",
        "import_foreign_app" to "این فایل با نسخه‌ی دیگری از قاجار وی پی ان ساخته شده است",
        "import_success" to "%d کانفیگ وارد شد",
        "import_open" to "باز کردن",
        "import_button" to "ورود",
        "locked_config" to "کانفیگ محافظت‌شده",
        "locked_note" to "این کانفیگ محافظت‌شده است. فقط می‌توانید نامش را تغییر دهید.",
        "selected" to "انتخاب‌شده",
        "delete_selected_q" to "کانفیگ‌های انتخاب‌شده حذف شوند؟",
        "copied" to "در کلیپ‌بورد کپی شد",
        "edit_config_title" to "ویرایش کانفیگ",
        "edit_sub_name" to "ویرایش نام",
        "service_name" to "نام سرویس gRPC",
        "mode" to "حالت",
        "alpn" to "ALPN (با کاما جدا کنید)",
        "fingerprint" to "اثر انگشت",
        "xray_logs" to "لاگ‌کت",
        "xray_logs_sub" to "مشاهده لاگ‌های اجرای موتور",
        "clear" to "پاک کردن",
        "no_logs" to "هنوز لاگی نیست",
        "stab_title" to "تست کیفیت اینترنت",
        "stab_sub" to "سرعت، پینگ، جیتر و کیفیت",
        "stab_start" to "شروع تست",
        "stab_stopping" to "در حال توقف…",
        "stab_ping" to "پینگ",
        "stab_dl_ping" to "پینگ دانلود",
        "stab_ul_ping" to "پینگ آپلود",
        "stab_jitter" to "جیتر",
        "stab_idle_latency" to "تاخیر idle",
        "stab_dl_latency" to "تأخیر دانلود",
        "stab_ul_latency" to "تأخیر آپلود",
        "stab_direct_checking" to "در حال بررسی شبکه مستقیم\u2026",
        "stab_direct_stable" to "شبکه مستقیم پایدار است",
        "stab_direct_unstable" to "شبکه مستقیم ناپایدار است",
        "stab_direct_offline" to "اتصال اینترنت قطع است",
        "stab_last_test" to "آخرین تست:",
        "stab_quality" to "کیفیت",
        "stab_q_excellent" to "عالی",
        "stab_q_good" to "خوب",
        "stab_q_fair" to "متوسط",
        "stab_q_poor" to "ضعیف",
        "stab_gaming" to "بازی",
        "stab_browsing" to "مرور وب",
        "stab_streaming" to "استریم",
        "stab_calling" to "تماس تصویری",
        "stab_through_tunnel" to "تست از طریق تونل",
        "stab_direct" to "تست اتصال مستقیم",
        "stab_failed" to "تست ناموفق بود — اتصال خود را بررسی کنید",
        "stab_testing_server" to "سرور تست:",
        "default_order" to "ترتیب پیش‌فرض",
        "fastest_first" to "سریع‌ترین",
        "routing" to "مسیریابی",
        "split_title" to "مسیریابی تفکیکی (ایران مستقیم)",
        "split_sub" to "سایت‌های ایرانی بدون تونل و مستقیم وصل می‌شوند.",
        "fragment_title" to "فرگمنت (ضد DPI)",
        "fragment_sub" to "TLS handshake را تکه‌تکه می‌کند تا از فیلترینگ SNI عبور کند. اگر سروری وصل نشد امتحان کنید.",
        "sniffing_title" to "روشن کردن Sniffing",
        "sniffing_type" to "نوع Sniffing",
        "sniffing_sub" to "به‌جای IP خام، با دامنه‌ای که از ترافیک تشخیص داده می‌شود متصل می‌شود. می‌تواند به اتصال درست برخی سرورها کمک کند.",
        "kill_switch_title" to "کیل سوئیچ",
        "mux_title" to "Mux (چندگانه‌سازی)",
        "mux_sub" to "چند اتصال را از یک جریان عبور می‌دهد. در شرایط فیلترینگ سنگین می‌تواند کمک کند، اما ممکن است سرعت را کم کند. با Reality/Vision خاموش بگذارید.",
        "mux_concurrency" to "حداکثر جریان همزمان",
        "kill_switch_sub" to "اگر وی‌پی‌ان به‌طور ناگهانی قطع شود، تمام اینترنت را مسدود می‌کند تا آی پی شما نشت نکند. برای بازگرداندن به حالت عادی، گزینه قطع اتصال را بزنید.",
        "always_on_title" to "فعال‌سازی System lock",
        "always_on_sub" to "برای کیل سوییچ کاملاً ضد نشت، در تنظیمات سیستم گزینه‌های «VPN همیشه‌روشن» و «مسدودسازی اتصال بدون VPN» را برای قاجار وی پی ان روشن کنید.",
        "globe_style_title" to "سبک کره زمین",
        "globe_style_filled" to "توپر",
        "globe_style_dots" to "نقطه‌ای",
        "theme_settings" to "تنظیمات ظاهری",
        "theme_settings_sub" to "ظاهر، تم اپ و کره زمین",
        "theme_mode" to "تم",
        "theme_light" to "روشن",
        "theme_dark" to "تیره",
        "theme_amoled" to "مشکی AMOLED",
        "theme_system" to "مطابق سیستم",
        "takes_effect" to "تغییرات از اتصال بعدی اعمال می‌شوند.",
        "language" to "زبان",
        "about" to "درباره",
        "about_sub" to "نسخه، توسعه‌دهنده و حریم خصوصی",
        "app_version" to "نسخه برنامه",
        "about_tagline" to "حریم خصوصی شاهانه، اتصال پایدار و مدیریت بومی سرویس",
        "xray_version" to "هسته Xray",
        "telegram_support" to "کانال تلگرام",
        "privacy_policy" to "سیاست حریم خصوصی",
        "developer" to "توسعه‌دهنده",
        "source_code" to "سورس کد",
        "check_updates" to "بررسی بروزرسانی",
        "checking_updates" to "در حال بررسی…",
        "up_to_date" to "نسخهٔ شما به‌روزترین است",
        "update_available" to "بروزرسانی موجود: %s",
        "update_failed" to "بررسی ناموفق بود — دوباره تلاش کنید",
        "update_now" to "بروزرسانی",
        "later" to "بعداً",
        "auto_refresh" to "بروزرسانی خودکار اشتراک‌ها",
        "auto_refresh_off" to "خاموش",
        "every_hour" to "هر %s ساعت",
        "every_hours" to "هر %s ساعت",
        "all_time_total" to "مجموع کل",
        "tap_ranges" to "برای بازه‌ها و تاریخ دلخواه بزنید  ›",
        "range" to "بازه",
        "today" to "امروز",
        "range_7d" to "۷ روز",
        "range_30d" to "۳۰ روز",
        "custom_range" to "بازه دلخواه",
        "from" to "از",
        "to" to "تا",
        "from_hour" to "از ساعت",
        "to_hour" to "تا ساعت",
        "custom_hint" to "تا ۲ روز جزئیات ساعتی و بیشتر از آن روزانه نمایش داده می‌شود. تاریخچه ساعتی حدود ۳۰ روز نگه داشته می‌شود.",
        "download" to "دانلود",
        "upload" to "آپلود",
        "total" to "مجموع",
        "no_data_range" to "داده‌ای برای این بازه نیست.",
        "tunnel_only" to "فقط ترافیک عبوری از تونل محاسبه می‌شود.",
        "peak_per_bar" to "اوج %s در هر ستون",
        "name_optional" to "نام (اختیاری)",
        "protocol" to "پروتکل",
        "address" to "آدرس",
        "port" to "پورت",
        "uuid" to "UUID",
        "password" to "رمز",
        "ikev2_user" to "نام کاربری",
        "ws_title" to "وینداسکرایب",
        "ws_intro" to "فهرست سرورها خودکار از وینداسکرایب گرفته می‌شود. مشخصات IKEv2 را وارد کنید، سرورهای دلخواه را انتخاب کنید تا هرکدام با آی‌پی به عنوان آدرس و دامنه به عنوان شناسه سرور اضافه شود.",
        "ws_credentials" to "مشخصات IKEv2",
        "ws_locations" to "لوکیشن سرورها",
        "ws_loading" to "در حال دریافت فهرست سرورها…",
        "ws_fetch_failed" to "فهرست سرورها دریافت نشد",
        "ws_need_host" to "حداقل یک آدرس پیست کنید",
        "ws_creds_hint" to "این‌ها را از windscribe.com/myaccount بخش Config Generators \u2192 IKEv2 بگیرید. با رمز ورود خود سایت و برنامه فرق دارند.",
        "ws_need_creds" to "ابتدا نام کاربری و رمز را وارد کنید",
        "ws_add_n" to "افزودن %s کانفیگ",
        "ws_added" to "%d کانفیگ افزوده شد",
        "ikev2_remote_id" to "شناسه سرور (دامنه)",
        "dbg_ikev2_nodebug" to "کانفیگ IKEv2 قابل دیباگ نیست",
        "ike_err_auth" to "احراز هویت ناموفق بود، نام کاربری و رمز را بررسی کنید",
        "ike_err_peer" to "احراز هویت سرور ناموفق بود",
        "ike_err_lookup" to "آدرس سرور ریزالو نشد",
        "ike_err_unreachable" to "سرور در دسترس نیست",
        "ike_err_password" to "رمز وارد نشده است",
        "ike_err_cert" to "سرتیفیکت در دسترس نیست",
        "ike_err_generic" to "اتصال ناموفق بود",
        "ikev2_note" to "IKEv2 روی موتور خودش اجرا می‌شود، پس پروکسی برنامه‌ها، مسیریابی تفکیکی و دیباگر کار نمی‌کنند.",
        "ikev2_bad_config" to "کانفیگ IKEv2 معتبر نیست",
        "enc_method" to "روش رمزگذاری",
        "flow_optional" to "Flow (اختیاری)",
        "network" to "شبکه",
        "security" to "امنیت",
        "sni" to "SNI / نام سرور",
        "public_key" to "کلید عمومی (pbk)",
        "short_id" to "شناسه کوتاه (sid)",
        "ws_path" to "مسیر WS",
        "ws_host" to "هدر Host برای WS",
        "cancel" to "لغو",
        "save" to "ذخیره",
        "err_address" to "آدرس الزامی است",
        "err_port" to "پورت باید بین ۱ تا ۶۵۵۳۵ باشد",
        "err_uuid" to "UUID الزامی است",
        "err_password" to "رمز الزامی است",
        "fetching_sub" to "در حال دریافت ساب…",
        "no_configs" to "کانفیگی پیدا نشد",
        "fetch_failed" to "دریافت ناموفق بود",
        "sub_err_http" to "سرور خطای %s برگرداند",
        "sub_err_empty" to "لینک چیزی برنگرداند",
        "sub_err_notconfig" to "این لینک فهرست کانفیگ نیست — آدرس را بررسی کنید",
        "sub_err_clash" to "این اشتراک Clash / sing-box است و پشتیبانی نمی‌شود",
        "parse_none" to "هیچ لینکی شناسایی نشد",
        "left" to "باقی‌مانده",
        "of" to "از",
        "expires_in" to "انقضا در",
        "unit_b" to "بایت",
        "unit_kb" to "کیلوبایت",
        "unit_mb" to "مگابایت",
        "unit_gb" to "گیگابایت",
        "unit_ms" to "میلی‌ثانیه",
        "unit_mbps" to "مگابیت بر ثانیه",
        "unit_per_sec" to " بر ثانیه",
        "unit_days" to "روز",
        "welcome_tagline" to "امنیت شاهانه، اتصال سریع",
        "welcome_dev" to "قاجار وی پی ان",
        "per_app" to "پروکسی برنامه‌ها",
        "per_app_sub" to "انتخاب کنید کدام برنامه‌ها از وی‌پی‌ان استفاده کنند",
        "per_app_mode" to "حالت",
        "per_app_off" to "خاموش",
        "per_app_allow" to "فقط انتخاب‌شده",
        "per_app_block" to "همه به‌جز",
        "per_app_off_hint" to "مسیریابی per-app خاموش است — همه برنامه‌ها از وی‌پی‌ان استفاده می‌کنند.",
        "per_app_empty_error" to "برای اتصال در حالت «فقط انتخاب‌شده»، حداقل یک برنامهٔ نصب‌شده را انتخاب کنید.",
        "search_apps" to "جستجوی برنامه‌ها",
        "search_servers" to "جستجوی سرورها",
        "appearance" to "ظاهر",
        "connection_settings" to "تنظیمات اتصال",
        "connection_settings_sub" to "مسیریابی، کیل‌سوییچ و پروکسی هر برنامه",
        "usage_by_config" to "مصرف بر اساس سرور",
        "usage_direct" to "مستقیم (بدون VPN)",
        "via_vpn" to "از طریق VPN",
        "smart_connect" to "اتصال هوشمند",
        "advanced" to "پیشرفته",
        "adblock_title" to "ادبلاکر و ضد ردیاب",
        "adblock_always_title" to "ادامه بلاک کردن هنگام قطع اتصال VPN",
        "adblock_always_sub" to "یک فیلتر لوکال بدون پروکسی اجرا می‌شود و ترافیک مستقیم می‌ماند",
        "adblock_notif" to "ادبلاکر",
        "fakedns_title" to "DNS فیک",
        "fakedns_sub" to "به هر دامنه یک آدرس جدا می‌دهد تا قوانین هر هاست همیشه اعمال شود",
        "encdns_title" to "DNS رمزنگاری‌شده",
        "encdns_sub" to "DNS Query از طریق DoH انجام می‌شود",
        "dns_leak_title" to "محافظت سخت‌گیرانه از نشت DNS",
        "dns_leak_sub" to "با فعال بودن DNS رمزنگاری‌شده، fallback ساده حذف می‌شود و DNS داخل مسیر VPN می‌ماند.",
        "ipv6_title" to "مدیریت IPv6",
        "ipv6_sub" to "IPv6 همیشه توسط قاجار گرفته می‌شود؛ آن را امن مسدود کن یا از تونل عبور بده.",
        "ipv6_block" to "مسدود (امن)",
        "ipv6_tunnel" to "از طریق VPN",
        "onion_title" to "مسیریابی سایت‌های Onion",
        "onion_sub" to "آدرس‌های onion. از طریق تور باز می‌شوند و بقیه ترافیک از سرور شما",
        "adblock_sub" to "دامنه‌های شناخته‌شده تبلیغاتی و ردیابی را داخل تونل مسدود می‌کند",
        "mixed_port" to "پورت میکس",
        "mixed_port_sub" to "پورت لوکال SOCKS/HTTP",
        "smart_connect_sub" to "هر دقیقه همه سرورها را تست و سریع‌ترین را انتخاب می‌کند",
        "preferences" to "شخصی‌سازی",
        "tools_sub" to "ادبلاکر، تست کیفیت، چک هاست و اتصال هوشمند",
        "netmon_title" to "رادار شبکه",
        "netmon_sub" to "بررسی مسدود بودن وبسایت‌ها روی شبکه فعلی شما",
        "chk_title" to "چک هاست",
        "chk_sub" to "اطلاعات و در دسترس بودن هر آدرس را بررسی کنید.",
        "chk_intro" to "اطلاعات و در دسترس بودن هر آدرس را بررسی کنید.",
        "chk_host" to "هاست یا آی‌پی",
        "chk_ping" to "پینگ",
        "chk_http" to "HTTP",
        "chk_tcp" to "TCP",
        "chk_start" to "شروع بررسی",
        "chk_running" to "در حال بررسی…",
        "chk_failed" to "دسترسی به check-host.net وجود ندارد",
        "chk_info" to "اطلاعات آدرس",
        "chk_ip" to "آی‌پی",
        "chk_asn" to "ASN",
        "chk_org" to "اپراتور",
        "chk_country" to "کشور",
        "chk_region" to "منطقه",
        "chk_city" to "شهر",
        "chk_tz" to "منطقه زمانی",
        "netmon_intro" to "به هر سایت از مسیر فعلی یک اتصال مستقیم باز می‌شود.",
        "netmon_via_tunnel" to "بررسی از داخل تونل",
        "netmon_via_direct" to "بررسی به‌صورت مستقیم (بدون VPN)",
        "netmon_up" to "در دسترس",
        "netmon_down" to "در دسترس نیست",
        "netmon_summary" to "%s از %s در دسترس",
        "netmon_testing" to "بررسی %s/%s",
        "netmon_recheck" to "بررسی دوباره",
        "netmon_sanctioned" to "تحریم/بلاک (۴۰۳)",
        "netcat_title" to "دسته‌بندی‌های بیشتر",
        "netcat_sub" to "بیش از ۱۱۰ سایت بیشتر برای تست",
        "netcat_ai" to "هوش مصنوعی",
        "netcat_news" to "خبری",
        "netcat_count" to "%s سایت",
        "netcat_gaming" to "بازی",
        "netcat_social" to "شبکه های اجتماعی",
        "netcat_trading" to "ترید",
        "netcat_iranian" to "پلتفرم‌های ایرانی",
        "preferences_sub" to "تم، زبان و بروزرسانی اشتراک",
        "sort_alpha" to "الفبایی",
        "sort_fastest" to "سریع‌ترین",
        "sort_added" to "زمان افزودن",
        "sort" to "مرتب‌سازی",
        "delete_all" to "حذف",
        "delete_manual_configs" to "حذف کانفیگ‌های دستی",
        "delete_everything" to "حذف همه چیز",
        "delete_manual_q" to "%s کانفیگ دستی حذف شود؟ اشتراک‌ها باقی می‌مانند.",
        "delete_everything_q" to "همه %s کانفیگ و تمام اشتراک‌ها حذف شود؟ این کار قابل بازگشت نیست.",
        "no_manual" to "کانفیگ دستی وجود ندارد",
        "delete_all_configs" to "حذف همه کانفیگ‌ها",
        "delete_timed_out" to "حذف تایم‌اوت‌ها",
        "delete_duplicates" to "حذف تکراری‌ها",
        "delete_duplicates_q" to "%s کانفیگ تکراری حذف شود؟ از هرکدام نسخه اول باقی می‌ماند.",
        "no_duplicates" to "کانفیگ تکراری پیدا نشد",
        "delete_all_q" to "همه %s کانفیگ حذف شود؟ این کار قابل بازگشت نیست.",
        "delete_timeout_q" to "%s کانفیگ تایم‌اوت حذف شود؟",
        "delete_sub_q" to "این اشتراک و هر %s کانفیگ آن حذف شود؟",
        "no_timed_out" to "کانفیگ تایم‌اوتی وجود ندارد — اول تست همه را بزنید",
        "deleted_n" to "%s کانفیگ حذف شد",
        "qr_share" to "اشتراک با کیوآر",
        "qr_title" to "برای وارد کردن اسکن کنید",
        "qr_hint" to "این کد را با دستگاه دیگر اسکن کنید تا کانفیگ اضافه شود",
        "qr_save" to "ذخیره تصویر",
        "qr_saved" to "تصویر کیوآر ذخیره شد",
        "qr_too_long" to "کانفیگ برای کیوآر کد خیلی بلند است",
        "scan_qr" to "اسکن کیوآر کد",
        "scan_qr_hint" to "دوربین را روی کد کانفیگ یا اشتراک بگیرید",
        "camera_needed" to "برای اسکن به دسترسی دوربین نیاز است",
        "camera_grant" to "دادن دسترسی",
        "qr_invalid" to "در این کد کانفیگی پیدا نشد",
        "backup_title" to "بکاپ‌گیری و بازگردانی",
        "backup_sub" to "ذخیره یا بازگرداندن همه چیز در یک فایل",
        "backup_export" to "ساخت فایل بکاپ",
        "backup_import" to "وارد کردن بکاپ",
        "backup_note" to "فایل بکاپ شامل سرورها، اشتراک‌ها و همه تنظیمات شماست. رمزنگاری شده و فقط داخل قاجار وی پی ان باز می‌شود.",
        "backup_creating" to "در حال ساخت بکاپ…",
        "backup_done" to "فایل بکاپ ذخیره شد",
        "backup_restored" to "%s کانفیگ و %s اشتراک اضافه شد شد",
        "backup_restore_q" to "وارد کردن فایل بکاپ، همه سرورها، اشتراک‌ها و تنظیمات فعلی را جایگزین می‌کند. ادامه می‌دهید؟",
        "backup_not_backup" to "این فایل کانفیگ اشتراکی است، نه بکاپ",
        "backup_failed" to "فایل بکاپ ساخته نشد",
        "loading_apps" to "در حال بارگذاری برنامه‌ها…",
    )

    fun get(lang: Lang, key: String): String =
        (if (lang == Lang.FA) fa[key] else en[key]) ?: en[key] ?: key
}
