#!/usr/bin/env bash
set -euo pipefail

package_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_root="$(cd "${1:?Usage: verify-source-snapshots.sh SOURCE_ROOT}" && pwd)"

# The readable GitHub files must be the same files that the patch series builds.
snapshots=(
  "app/src/androidTest/java/net/gozar/app/ExampleInstrumentedTest.kt"
  "app/src/androidTest/java/net/gozar/app/GhajarAndroid14RegressionTest.kt"
  "app/src/main/java/net/gozar/app/DotGlobe.kt"
  "app/src/main/java/net/gozar/app/GhajarAppearance.kt"
  "app/src/main/java/net/gozar/app/GhajarLocation.kt"
  "app/src/main/java/net/gozar/app/GhajarLocationRules.kt"
  "app/src/main/java/net/gozar/app/Globe.kt"
  "app/src/main/java/net/gozar/app/MainActivity.kt"
  "app/src/main/res/drawable/ghajar_launcher_layer.xml"
  "app/src/main/res/drawable/ghajar_launcher_mono.xml"
  "app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml"
  "app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml"
  "app/src/test/java/net/gozar/app/GhajarLocationRulesTest.kt"
  "app/build.gradle.kts"
  "openvpn/build.gradle.kts"
  "strongswan/build.gradle.kts"
  "settings.gradle.kts"
  "app/src/main/java/net/gozar/app/BrandConfig.kt"
  "app/src/main/java/net/gozar/app/GhajarAccountStore.kt"
  "app/src/main/java/net/gozar/app/GhajarNotificationMonitor.kt"
  "app/src/main/java/net/gozar/app/GhajarShopScreen.kt"
  "app/src/main/java/net/gozar/app/GhajarSplashRepository.kt"
  "app/src/main/java/net/gozar/app/GhajarStoreApi.kt"
  "app/src/main/java/net/gozar/app/SecurePaymentActivity.kt"
  "app/src/main/java/net/gozar/app/GhajarUiRules.kt"
  "app/src/main/java/net/gozar/app/GhajarLinkFlow.kt"
  "app/src/main/java/net/gozar/app/GhajarVisuals.kt"
  "app/src/main/java/net/gozar/app/GhajarWelcomeAssets.kt"
  "app/src/main/java/net/gozar/app/GhajarNoticeBanner.kt"
  "app/src/main/java/net/gozar/app/GhajarSelectedServerCard.kt"
  "app/src/main/java/net/gozar/app/GhajarCheckoutViewModel.kt"
  "app/src/main/java/net/gozar/app/GhajarCheckoutCards.kt"
  "app/src/main/java/net/gozar/app/GhajarOperation.kt"
  "app/src/main/java/net/gozar/app/GhajarPaymentPolicy.kt"
  "app/src/test/java/net/gozar/app/GhajarCommerceRulesTest.kt"
  "app/src/test/java/net/gozar/app/GhajarUiRulesTest.kt"
  "app/src/test/java/net/gozar/app/GhajarLinkFlowTest.kt"
  "app/src/main/AndroidManifest.xml"
  "app/src/main/java/net/gozar/app/ConfigStore.kt"
  "app/src/main/java/net/gozar/app/GhajarImportRules.kt"
  "app/src/main/java/net/gozar/app/GhajarOpenVpnBridge.kt"
  "app/src/main/java/net/gozar/app/GhajarWidgetProvider.kt"
  "app/src/main/java/net/gozar/app/Gozarapplication.kt"
  "app/src/main/java/net/gozar/app/Qstileservice.kt"
  "app/src/main/java/net/gozar/app/SpeedTest.kt"
  "app/src/main/java/net/gozar/app/StabilityTest.kt"
  "app/src/main/java/net/gozar/app/Strings.kt"
  "app/src/main/java/net/gozar/app/Subscriptionrefresher.kt"
  "app/src/main/java/net/gozar/app/VpnConnectionStore.kt"
  "app/src/main/java/net/gozar/app/VpnState.kt"
  "app/src/main/java/net/gozar/app/Vpnbridge.kt"
  "app/src/main/res/drawable/ghajar_launch_background.xml"
  "app/src/main/res/drawable/ghajar_widget_background.xml"
  "app/src/main/res/drawable/ghajar_widget_button.xml"
  "app/src/main/res/layout/ghajar_widget_control.xml"
  "app/src/main/res/layout/ghajar_widget_small.xml"
  "app/src/main/res/values-v31/themes.xml"
  "app/src/main/res/values/themes.xml"
  "app/src/main/res/values/widget_styles.xml"
  "app/src/main/res/xml/ghajar_widget_control_info.xml"
  "app/src/main/res/xml/ghajar_widget_small_info.xml"
  "app/src/test/java/net/gozar/app/GhajarImportRulesTest.kt"
  "app/src/test/java/net/gozar/app/SpeedTestRulesTest.kt"
  "openvpn/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java"
  "openvpn/src/main/cpp/CMakeLists.txt"
  "openvpn/src/main/cpp/ghajar-openssl-arch.cmake"
)
for path in "${snapshots[@]}"; do
  if ! cmp -s -- "${package_root}/${path}" "${source_root}/${path}"; then
    echo "Snapshot differs from materialized source: ${path}" >&2
    exit 1
  fi
done
echo "Verified ${#snapshots[@]} reviewed source snapshots."
